// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/julienschmidt/httprouter"
	"net/http"
	"user-management-test/controller"
	"user-management-test/helper"
	"user-management-test/repository"
	"user-management-test/service"
)

// Injectors from injector.go:

func InitServer() (*http.Server, func(), error) {
	userRepository := repository.NewUserRepository()
	db, cleanup, err := helper.NewDb()
	if err != nil {
		return nil, nil, err
	}
	userService := service.NewUserService(userRepository, db)
	userController := controller.NewUserController(userService)
	router := NewRouter(userController)
	server := NewServer(router)
	return server, func() {
		cleanup()
	}, nil
}

// injector.go:

var ServerSet = wire.NewSet(repository.NewUserRepository, service.NewUserService, controller.NewUserController, helper.NewDb, NewRouter, wire.Bind(new(http.Handler), new(*httprouter.Router)), NewServer)
